#!/bin/bash

# Run the styles and javascript files on different servers as the parcel
# will compile the folder hierarchy if done together. To keep everything at
# the same level, compile the separate style files and browser-sync
# takes care of keeping your browser in sync when any type of file changes.
#
# @author Fonoster
#
development() {
  local ENTRY_POINT=$1
  local STYLES=$2

  [[ -z "$*" ]] && error "No arguments provided"

  info "Building application and resources in development mode, from the entry point: $ENTRY_POINT"

  rimraf ./dist

  if [[ ! -f app.config.json ]]; then
    info "Copying the development configuration... 🔧"
    cp ./.config/develop.config.json ./app.config.json
  fi

  concurrently -n "Styles,Widget,Browsersync" \
    "parcel watch $STYLES --no-source-maps" \
    "parcel serve $ENTRY_POINT --port 3085 --no-source-maps" \
    "browser-sync start --proxy localhost:3085 --port 3080 --files src"

  exit 0
}
