#!/bin/bash

prepare_production() {
  info "Deploying to prod envinronment... 🚀 "

  info "Install Dependencies 🔧"
  yarn install

  if [[ ! -f app.config.json ]]; then
    info "Copying the production configuration... 🔧"
    cp ./.config/production.config.json ./app.config.json
  fi

  info "Build and remove debugging dependencies 🔧"
  yarn ci:build
}
