#!/bin/bash

set -e

BASE_DIR=$(dirname "$0")

# Import sources function
source "$BASE_DIR/bin/import.sh"

# Import scripts
import "$BASE_DIR/**/*"
import "$BASE_DIR/**/**/*"

INPUT=$1
shift

COMMAND=$(echo "$INPUT" | awk '{print tolower($0)}')

info "Development Management (Roxanne Assistant) - Current OS: $OS"

case $COMMAND in
web:start)
  web_start
  ;;
web:build)
  web_build
  ;;
voice:start)
  voice_start
  ;;
voice:build)
  voice_build
  ;;
setup)
  setup
  ;;
patch | patch-line)
  patch_line
  ;;
lint | linters)
  linters
  ;;
branch-name | branch)
  is_valid_branch
  ;;
help)
  help
  ;;
*)
  error "Unknown command: $COMMAND"
  ;;
esac
