#!/bin/bash

set -e

BASE_DIR=$(dirname "$0")

# Import sources function
source "$BASE_DIR/bin/import"

# Import scripts
import "$BASE_DIR/**/*"

# Globals
WIDGET_PATH="src/widget.ts"
ENTRY_POINT_PATH="public/index.html"
STYLES_PATH="src/ui/styles/*.scss"

INPUT=$1
shift

COMMAND=$(echo "$INPUT" | awk '{print tolower($0)}')

info "Development Management (Roxanne Assistant) - Current OS: $OS"

case $COMMAND in
staging | deploy:staging)
  prepare_staging
  ;;
production | deploy:production | prod)
  prepare_production
  ;;
start | dev | watch | develop)
  development "$ENTRY_POINT_PATH" "$STYLES_PATH"
  ;;
build)
  build "$WIDGET_PATH" "$STYLES_PATH"
  ;;
patch | patch-line)
  patch_line
  ;;
lint | linters)
  linters
  ;;
branch-name | branch)
  is_valid_branch
  ;;
help)
  help
  ;;
*)
  error "Unknown command: $COMMAND"
  ;;
esac
