name: Pull Request - CI
on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  linters-and-tests:
    name: Run linters and tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2.3.1

      - name: Install Dependencies
        run: |
          yarn install

      - name: Run linters
        run: |
          yarn git:pre-commit
