name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release process
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2.3.1

      - name: Install Dependencies
        run: |
          yarn install

      - name: Build and remove debugging dependencies
        run: |
          yarn ci:build

      - name: Create zip with compiled files
        run: |
          zip -j widget dist/*

      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::$(node -e "console.log(require('./package.json').version)")

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ steps.get_version.outputs.VERSION }}"
          release_name: "Release v${{ steps.get_version.outputs.VERSION }}"
          draft: false
          prerelease: false

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./widget.zip
          asset_name: widget.zip
          asset_content_type: application/zip
